"""removes layout table and updates metric table pk

Revision ID: 60feb0050151
Revises: 93a64196dc9f
Create Date: 2025-07-27 04:42:21.139846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60feb0050151'
down_revision: Union[str, Sequence[str], None] = '93a64196dc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layouts')
    op.alter_column('metrics', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_table('layouts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('screen_size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('w', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('h', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('static', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['metrics.id'], name=op.f('layouts_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'screen_size', name=op.f('layouts_pkey'))
    )
    # ### end Alembic commands ###
