"""Remakes the database

Revision ID: 70a0ba94bd55
Revises: d7eadee9dda8
Create Date: 2025-07-27 04:58:13.860641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a0ba94bd55'
down_revision: Union[str, Sequence[str], None] = 'd7eadee9dda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id', 'query_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('queries')
    # ### end Alembic commands ###
