"""Add all tables

Revision ID: 93a64196dc9f
Revises: eeabe27bf226
Create Date: 2025-07-27 02:48:25.834378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a64196dc9f'
down_revision: Union[str, Sequence[str], None] = 'eeabe27bf226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_size', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('static', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id', 'screen_size')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layouts')
    op.drop_table('metrics')
    op.drop_table('queries')
    # ### end Alembic commands ###
